{% set name = "TPOT" %}
{% set version = "0.9.4" %}
{% set sha256 = "88c4ea9b76b4cb288861ec231a1a6082ec0dfa045101d25a5b0725db3e75a3a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - tpot=tpot:main

requirements:
  build:
    - python
    - setuptools

  run:
    - deap >=1.0
    - numpy >=1.12.1
    - pandas >=0.20.2
    - python
    - scikit-learn >=0.18.1
    - scipy >=0.19.0
    - stopit >=1.1.1
    - tqdm >=4.11.2
    - update_checker >=0.16
    - pywin32  # [win]

test:
  requires:
    - nose
    - python
    - py-xgboost
    - scikit-mdr
    - skrebate
  source_files:
    - tests
  imports:
    - tpot
    - tpot.base
    - tpot.builtins
    - tpot.config
    - tpot.decorators
    - tpot.driver
    - tpot.export_utils
    - tpot.gp_deap
    - tpot.gp_types
    - tpot.metrics
    - tpot.operator_utils
    - tpot.tpot
  commands:
    - tpot --help
    - tpot --version
    - nosetests tests

about:
  home: https://rhiever.github.io/tpot/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python tool that automatically creates and optimizes Machine Learning pipelines using genetic programming.'
  dev_url: https://github.com/rhiever/tpot
  description: |
    Consider TPOT your Data Science Assistant. TPOT is a Python Automated
    Machine Learning tool that optimizes machine learning pipelines using
    genetic programming.

    TPOT will automate the most tedious part of machine learning by
    intelligently exploring thousands of possible pipelines to find the best
    one for your data.

    Once TPOT is finished searching (or you get tired of waiting), it provides
    you with the Python code for the best pipeline it found so you can tinker
    with the pipeline from there.

    TPOT is built on top of scikit-learn, so all of the code it generates
    should look familiar... if you're familiar with scikit-learn, anyway.

    TPOT is still under active development and we encourage you to check back
    on this repository regularly for updates.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
