{% set tpot_python = ">=3.5" %}
{% set version = "0.12.1" %}
{% set tpot_python = ">=3.5" %}

package:
  name: tpot-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/TPOT/TPOT-{{ version }}.tar.gz
  sha256: f5b54bf04a150e4c3c8aaa1b26d8492b0837c9c50fa0b3b603106a6d623654cc

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ tpot_python }}

test:
  commands:
    - echo "the subpackages are tested"

outputs:
  - name: tpot

    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      entry_points:
        - tpot = tpot:main

    requirements:
      host:
        - pip
        - python {{ tpot_python }}
      run:
        - deap >=1.2
        - joblib >=0.13.2
        - numpy >=1.16.3
        - pandas >=0.24.2
        - py-xgboost >=1.1.0
        - python {{ tpot_python }}
        - scikit-learn >=0.22.0
        - scipy >=1.3.1
        - stopit >=1.1.2
        - tqdm >=4.36.1
        - update_checker >=0.16

    test:
      requires:
        - pip
      imports:
        - tpot
      commands:
        - pip check
        - tpot --version
        - tpot --help

  - name: tpot-skrebate
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot', exact=True) }}
        - python {{ tpot_python }}
        - skrebate >=0.3.4
    test:
      imports:
        - tpot
      requires:
        - pip
      commands:
        - pip check

  - name: tpot-mdr
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot', exact=True) }}
        - python {{ tpot_python }}
        - scikit-mdr >=0.4.4
    test:
      imports:
        - tpot
      requires:
        - pip
      commands:
        - pip check

  - name: tpot-dask
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot', exact=True) }}
        - dask >=0.18.2
        - dask-ml >=1.0.0
        - distributed >=1.22.1
        - python {{ tpot_python }}
    test:
      imports:
        - tpot
      requires:
        - pip
      commands:
        - pip check

  - name: tpot-torch
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot', exact=True) }}
        - python {{ tpot_python }}
        - pytorch
    test:
      imports:
        - tpot.builtins.nn
      requires:
        - pip
      commands:
        - pip check

  - name: tpot-imblearn
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot', exact=True) }}
        - imbalanced-learn >=0.7.0
        - python {{ tpot_python }}
    test:
      imports:
        - tpot
      requires:
        - pip
      commands:
        - pip check

  - name: tpot-full
    build:
      noarch: python
    requirements:
      host:
        - python {{ tpot_python }}
      run:
        - {{ pin_subpackage('tpot-dask', exact=True) }}
        - {{ pin_subpackage('tpot-imblearn', exact=True) }}
        - {{ pin_subpackage('tpot-mdr', exact=True) }}
        - {{ pin_subpackage('tpot-skrebate', exact=True) }}
        - {{ pin_subpackage('tpot-torch', exact=True) }}
        - {{ pin_subpackage('tpot', exact=True) }}
        - python {{ tpot_python }}
    test:
      imports:
        - tpot
      requires:
        - nose
        - pip
        # TODO: newer versions fail due to (pre-announced) hard deprecation of `load_boston`, and upstream pins break `dask-ml`
        - scikit-learn <1.2.0
        - dask-ml <2023.3.24
      source_files:
        - tests
      commands:
        - pip check
        - nosetests tests -s -v -e test_dask_matches -e test_StackingEstimator_4 -e test_sample_weight_func -e one_hot_encoder_tests -e test_score_2 -e test_varOr -e test_mate_operator -e test_get_params -e test_mate_operator_stats_update

about:
  home: https://epistasislab.github.io/tpot
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python tool that automatically creates and optimizes Machine Learning pipelines using genetic programming.'
  dev_url: https://github.com/EpistasisLab/tpot
  description: |
    Consider TPOT your Data Science Assistant. TPOT is a Python Automated
    Machine Learning tool that optimizes machine learning pipelines using
    genetic programming.

    TPOT will automate the most tedious part of machine learning by
    intelligently exploring thousands of possible pipelines to find the best
    one for your data.

    Once TPOT is finished searching (or you get tired of waiting), it provides
    you with the Python code for the best pipeline it found so you can tinker
    with the pipeline from there.

    TPOT is built on top of scikit-learn, so all of the code it generates
    should look familiar... if you're familiar with scikit-learn, anyway.

    TPOT is still under active development and we encourage you to check back
    on this repository regularly for updates.

extra:
  feedstock-name: tpot
  recipe-maintainers:
    - proinsias
    - bollwyvl
    - jay-m-dev
